management.endpoints.web.exposure.include=health,prometheus

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

springdoc.api-docs.info.title=Antivirus server API
springdoc.api-docs.info.version=1.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_EXP:900000}
jwt.refresh.expiration=${REF_EXP:2592000000}

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:server.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=${SERVER_PASS}
server.ssl.key-alias=server

signature:
  key-store-path: classpath:signing.jks
  key-store-type: JKS
  key-store-password: ${SIGNING_STORE_PASS}
  key-alias: ${ALIAS}
  key-password: ${KEY_PASSWORD}